"""Tabulate the v2-mini CdA-sensitivity result.

Consumes the two off-baseline parquets produced by `sweep.cda_sensitivity`
(``outputs/all_runs_cda_{low,high}.parquet``) together with the v2-mini
slice of the main-sweep aggregate at the baseline subset
(``outputs/all_runs.parquet``), and emits:

- ``src/tex/tables/tab_cda_sensitivity.tex`` — booktabs LaTeX table of
  median ``|Δr|_hifi`` per ``(alt_shell × Δt bucket)`` cell at the three
  CdA factors. Empty cells (e.g. 540 km × v2-mini absent in the corpus)
  render as ``---``.
- ``outputs/cda_sensitivity_summary.json`` — same numbers in machine
  form, plus pooled medians and an overall "max relative shift vs.
  baseline" figure suitable for inlining in the PR description and §5
  prose.

The baseline restriction is critical: only the subset-and-v2-mini slice
of ``all_runs.parquet`` is comparable, since the off-baseline frames
were run on exactly that slice. The driver loads the subset id file and
filters before joining; mismatched ID-set sizes raise loudly.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Final

import numpy as np
import pandas as pd

GENERATION_V2_MINI: Final = "v2-mini"
BUCKET_LABELS: Final = {
    21_600: "6 h",
    86_400: "1 d",
    259_200: "3 d",
    604_800: "7 d",
}


def _load_baseline_v2_mini(
    all_runs_path: Path,
    subset_ids_path: Path,
) -> pd.DataFrame:
    """v2-mini slice of all_runs.parquet restricted to the sensitivity subset.

    The main-sweep aggregate carries ``generation`` post-join; the
    sensitivity-subset id file is the run-id list defined by
    ``sweep.sensitivity_subset``. We filter on both to land on the same
    pairs the off-baseline driver ran on.
    """
    all_runs = pd.read_parquet(all_runs_path)
    ids = {int(x) for x in subset_ids_path.read_text().splitlines() if x.strip()}
    v2_mini = all_runs[
        (all_runs["generation"] == GENERATION_V2_MINI) & (all_runs["run_id"].isin(ids))
    ].copy()
    v2_mini["cda_factor"] = 1.0
    return v2_mini


def _validate_alignment(
    baseline: pd.DataFrame,
    low: pd.DataFrame,
    high: pd.DataFrame,
) -> None:
    """Confirm the three frames cover the same v2-mini run_id set.

    If the off-baseline driver missed runs (GMAT failure, postprocess
    gap), refuse to render a table off a partial set — the per-cell
    medians would compare different subpopulations.
    """
    sets = {
        "baseline": set(baseline["run_id"].astype(int)),
        "low": set(low["run_id"].astype(int)),
        "high": set(high["run_id"].astype(int)),
    }
    sizes = {k: len(v) for k, v in sets.items()}
    if sizes["low"] != sizes["baseline"] or sizes["high"] != sizes["baseline"]:
        raise SystemExit(
            "CdA-sensitivity frames have different run_id counts: "
            f"{sizes}. Re-run `make cda-sensitivity` to repopulate the "
            "off-baseline frames.",
        )
    missing_low = sets["baseline"] - sets["low"]
    missing_high = sets["baseline"] - sets["high"]
    if missing_low or missing_high:
        raise SystemExit(
            "CdA-sensitivity frames miss baseline run_ids: "
            f"low-missing={sorted(missing_low)[:5]}, "
            f"high-missing={sorted(missing_high)[:5]}",
        )


def _per_cell_medians(combined: pd.DataFrame) -> pd.DataFrame:
    """Median |Δr|_hifi per (alt_shell, target_dt_sec, cda_factor)."""
    out = (
        combined.groupby(["alt_shell", "target_dt_sec", "cda_factor"], sort=True)["dr_hifi_km"]
        .agg(["median", "count"])
        .rename(columns={"median": "median_km", "count": "n"})
        .reset_index()
    )
    return out


def _pivot_for_table(per_cell: pd.DataFrame) -> pd.DataFrame:
    """Wide table indexed by (alt_shell, target_dt_sec), columns = factor."""
    wide = per_cell.pivot_table(
        index=["alt_shell", "target_dt_sec"],
        columns="cda_factor",
        values="median_km",
        aggfunc="first",
    )
    wide = wide.reindex(columns=[0.8, 1.0, 1.2])
    return wide


def _fmt_shift(median: float, baseline: float) -> str:
    if not np.isfinite(median) or not np.isfinite(baseline) or baseline == 0.0:
        return "---"
    rel = (median - baseline) / baseline * 100.0
    return f"{rel:+.1f}\\%"


def render_latex_table(pivot: pd.DataFrame) -> str:
    """booktabs LaTeX. Median |Δr|_hifi per (shell × Δt) at CdA × {0.8, 1.0, 1.2}.

    Lays out shells as ``midrule``-separated blocks of four buckets, with
    a row per (shell, bucket). Columns: bucket, baseline (1.0×), low (0.8×)
    with relative shift, high (1.2×) with relative shift. Empty cells
    (no pairs at that stratum) render as ``---``.
    """
    lines = [
        "% Generated by sweep.cda_sensitivity_table — do not edit by hand.",
        "\\begin{tabular}{llrrr}",
        "\\toprule",
        "Shell & $\\Delta t$ & "
        "$\\mathrm{med}\\,|\\Delta\\mathbf{r}|_{\\mathrm{hifi}}$ "
        "(1.0$\\times$) & "
        "0.8$\\times$ shift & "
        "1.2$\\times$ shift \\\\",
        "(km) & & (km) & (vs.\\ baseline) & (vs.\\ baseline) \\\\",
        "\\midrule",
    ]
    shells = sorted(pivot.index.get_level_values("alt_shell").unique())
    for i, shell in enumerate(shells):
        block = pivot.loc[shell]
        for target_dt_sec, row in block.iterrows():
            bucket = BUCKET_LABELS.get(int(target_dt_sec), f"{int(target_dt_sec)} s")
            baseline = float(row.get(1.0, np.nan))
            low = float(row.get(0.8, np.nan))
            high = float(row.get(1.2, np.nan))
            baseline_cell = f"{baseline:.2f}" if np.isfinite(baseline) else "---"
            low_cell = _fmt_shift(low, baseline)
            high_cell = _fmt_shift(high, baseline)
            lines.append(
                f"{shell} & {bucket} & {baseline_cell} & {low_cell} & {high_cell} \\\\",
            )
        if i < len(shells) - 1:
            lines.append("\\midrule")
    lines.extend(["\\bottomrule", "\\end{tabular}"])
    return "\n".join(lines) + "\n"


def compute_summary(per_cell: pd.DataFrame) -> dict:
    """Headline numbers consumed by the PR body and §5 prose.

    Returns pooled per-factor medians, per-cell relative shifts, the
    sign of every shift (so the §5 paragraph can claim "every cell
    moves in the expected direction" or qualify if not), and the
    maximum absolute relative shift across cells.
    """
    pooled_baseline = float(
        per_cell.loc[per_cell["cda_factor"] == 1.0, "median_km"].median(),
    )
    pooled_low = float(per_cell.loc[per_cell["cda_factor"] == 0.8, "median_km"].median())
    pooled_high = float(per_cell.loc[per_cell["cda_factor"] == 1.2, "median_km"].median())

    by_cell: dict[str, dict] = {}
    max_abs_shift = 0.0
    sign_low_consistent = True
    sign_high_consistent = True
    for (shell, target_dt_sec), group in per_cell.groupby(
        ["alt_shell", "target_dt_sec"],
        sort=True,
    ):
        baseline_rows = group[group["cda_factor"] == 1.0]
        if baseline_rows.empty:
            continue
        baseline = float(baseline_rows["median_km"].iloc[0])
        cell = {"baseline_km": baseline, "n": int(baseline_rows["n"].iloc[0])}
        for factor in (0.8, 1.2):
            sub = group[group["cda_factor"] == factor]
            if sub.empty or baseline == 0.0:
                continue
            median_km = float(sub["median_km"].iloc[0])
            rel = (median_km - baseline) / baseline
            cell[f"factor_{factor:g}"] = {
                "median_km": median_km,
                "relative_shift": rel,
            }
            max_abs_shift = max(max_abs_shift, abs(rel))
            if factor == 0.8 and rel > 0:
                sign_low_consistent = False
            if factor == 1.2 and rel < 0:
                sign_high_consistent = False
        by_cell[f"{shell}_{int(target_dt_sec)}"] = cell

    return {
        "pooled_baseline_km": pooled_baseline,
        "pooled_cda_low_km": pooled_low,
        "pooled_cda_high_km": pooled_high,
        "pooled_relative_shift_low": (
            (pooled_low - pooled_baseline) / pooled_baseline if pooled_baseline else float("nan")
        ),
        "pooled_relative_shift_high": (
            (pooled_high - pooled_baseline) / pooled_baseline if pooled_baseline else float("nan")
        ),
        "max_abs_relative_shift": max_abs_shift,
        "sign_low_negative_consistent": sign_low_consistent,
        "sign_high_positive_consistent": sign_high_consistent,
        "by_cell": by_cell,
    }


def build(
    all_runs_path: Path,
    cda_low_path: Path,
    cda_high_path: Path,
    subset_ids_path: Path,
) -> tuple[str, dict]:
    """End-to-end: load three frames, build the table and summary."""
    baseline = _load_baseline_v2_mini(all_runs_path, subset_ids_path)
    low = pd.read_parquet(cda_low_path)
    high = pd.read_parquet(cda_high_path)
    _validate_alignment(baseline, low, high)

    keep_cols = ["run_id", "alt_shell", "target_dt_sec", "cda_factor", "dr_hifi_km"]
    combined = pd.concat(
        [baseline[keep_cols], low[keep_cols], high[keep_cols]],
        ignore_index=True,
    )
    per_cell = _per_cell_medians(combined)
    pivot = _pivot_for_table(per_cell)
    return render_latex_table(pivot), compute_summary(per_cell)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--all-runs",
        type=Path,
        default=Path("outputs/all_runs.parquet"),
    )
    parser.add_argument(
        "--cda-low",
        type=Path,
        default=Path("outputs/all_runs_cda_low.parquet"),
    )
    parser.add_argument(
        "--cda-high",
        type=Path,
        default=Path("outputs/all_runs_cda_high.parquet"),
    )
    parser.add_argument(
        "--subset-ids",
        type=Path,
        default=Path("src/static/sensitivity_subset_pair_ids.txt"),
    )
    parser.add_argument(
        "--table-out",
        type=Path,
        default=Path("src/tex/tables/tab_cda_sensitivity.tex"),
    )
    parser.add_argument(
        "--summary-out",
        type=Path,
        default=Path("outputs/cda_sensitivity_summary.json"),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    table_latex, summary = build(
        args.all_runs,
        args.cda_low,
        args.cda_high,
        args.subset_ids,
    )
    args.table_out.parent.mkdir(parents=True, exist_ok=True)
    args.table_out.write_text(table_latex, encoding="utf-8")
    args.summary_out.parent.mkdir(parents=True, exist_ok=True)
    args.summary_out.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(
        f"wrote {args.table_out} and {args.summary_out}; "
        f"max |relative shift| = {summary['max_abs_relative_shift'] * 100:.1f}%",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
